title: Abi Green
email: abiverderci@gmail.com
description: >-
baseurl: ""
url: "https://abiver.de"  # your domain
show_social_links: true
github_username: "abi-klevu"
linkedin_username: "abiverde"
instagram_username: "abiverde"
logo: "assets/img/abi-pfp.jpg"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

