title: Abi Green
email: abiverderci@gmail.com
description: >-
  Placeholder site
baseurl: ""
url: "https://abiver.de"   # use https and your correct domain
twitter_username: dajve
github_username: dajve

# Theme config
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

