title: Abi Green
email: abiverderci@gmail.com
description: >-
baseurl: ""
url: "https://abiver.de"  # your domain
twitter_username: dajve
github_username: dajve

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

